export const COUNTRY_NAMES: { [key: string]: string } = {
  'NO': 'Norway', 'SE': 'Sweden', 'DK': 'Denmark', 'FI': 'Finland', 'IS': 'Iceland',
  'DE': 'Germany', 'FR': 'France', 'IT': 'Italy', 'ES': 'Spain', 'PT': 'Portugal',
  'NL': 'Netherlands', 'BE': 'Belgium', 'LU': 'Luxembourg', 'AT': 'Austria', 'CH': 'Switzerland',
  'GB': 'United Kingdom', 'IE': 'Ireland', 'PL': 'Poland', 'CZ': 'Czech Republic', 'SK': 'Slovakia',
  'HU': 'Hungary', 'SI': 'Slovenia', 'HR': 'Croatia', 'RO': 'Romania', 'BG': 'Bulgaria',
  'GR': 'Greece', 'CY': 'Cyprus', 'MT': 'Malta', 'EE': 'Estonia', 'LV': 'Latvia',
  'LT': 'Lithuania', 'US': 'United States', 'CA': 'Canada', 'AU': 'Australia', 'JP': 'Japan',
  'CN': 'China', 'IN': 'India', 'BR': 'Brazil', 'MX': 'Mexico', 'AR': 'Argentina',
  'CL': 'Chile', 'PE': 'Peru', 'CO': 'Colombia', 'VE': 'Venezuela', 'UY': 'Uruguay',
  'PY': 'Paraguay', 'BO': 'Bolivia', 'EC': 'Ecuador', 'GY': 'Guyana', 'SR': 'Suriname',
  'ZA': 'South Africa', 'EG': 'Egypt', 'MA': 'Morocco', 'TN': 'Tunisia', 'DZ': 'Algeria',
  'LY': 'Libya', 'SD': 'Sudan', 'ET': 'Ethiopia', 'KE': 'Kenya', 'UG': 'Uganda',
  'TZ': 'Tanzania', 'RW': 'Rwanda', 'BI': 'Burundi', 'DJ': 'Djibouti', 'SO': 'Somalia',
  'ER': 'Eritrea', 'SS': 'South Sudan', 'CF': 'Central African Republic', 'TD': 'Chad',
  'NE': 'Niger', 'ML': 'Mali', 'BF': 'Burkina Faso', 'SN': 'Senegal', 'GM': 'Gambia',
  'GW': 'Guinea-Bissau', 'GN': 'Guinea', 'SL': 'Sierra Leone', 'LR': 'Liberia', 'CI': 'Côte d\'Ivoire',
  'GH': 'Ghana', 'TG': 'Togo', 'BJ': 'Benin', 'NG': 'Nigeria', 'CM': 'Cameroon',
  'GQ': 'Equatorial Guinea', 'GA': 'Gabon', 'CG': 'Republic of the Congo', 'CD': 'DR Congo',
  'AO': 'Angola', 'ZM': 'Zambia', 'ZW': 'Zimbabwe', 'BW': 'Botswana', 'NA': 'Namibia',
  'SZ': 'Eswatini', 'LS': 'Lesotho', 'MG': 'Madagascar', 'MU': 'Mauritius', 'SC': 'Seychelles',
  'KM': 'Comoros', 'MZ': 'Mozambique', 'MW': 'Malawi', 'TR': 'Turkey', 'RU': 'Russia',
  'UA': 'Ukraine', 'BY': 'Belarus', 'MD': 'Moldova', 'GE': 'Georgia', 'AM': 'Armenia',
  'AZ': 'Azerbaijan', 'KZ': 'Kazakhstan', 'UZ': 'Uzbekistan', 'TM': 'Turkmenistan',
  'TJ': 'Tajikistan', 'KG': 'Kyrgyzstan', 'AF': 'Afghanistan', 'PK': 'Pakistan',
  'IR': 'Iran', 'IQ': 'Iraq', 'SY': 'Syria', 'LB': 'Lebanon', 'JO': 'Jordan',
  'IL': 'Israel', 'PS': 'Palestine', 'SA': 'Saudi Arabia', 'YE': 'Yemen', 'OM': 'Oman',
  'AE': 'United Arab Emirates', 'QA': 'Qatar', 'BH': 'Bahrain', 'KW': 'Kuwait',
  'KR': 'South Korea', 'KP': 'North Korea', 'MN': 'Mongolia', 'TH': 'Thailand',
  'VN': 'Vietnam', 'LA': 'Laos', 'KH': 'Cambodia', 'MM': 'Myanmar', 'MY': 'Malaysia',
  'SG': 'Singapore', 'BN': 'Brunei', 'ID': 'Indonesia', 'TL': 'East Timor', 'PH': 'Philippines',
  'TW': 'Taiwan', 'HK': 'Hong Kong', 'MO': 'Macao', 'NZ': 'New Zealand', 'FJ': 'Fiji',
  'PG': 'Papua New Guinea', 'SB': 'Solomon Islands', 'VU': 'Vanuatu', 'NC': 'New Caledonia',
  'PF': 'French Polynesia', 'WS': 'Samoa', 'TO': 'Tonga', 'CK': 'Cook Islands',
  'NU': 'Niue', 'PW': 'Palau', 'FM': 'Micronesia', 'MH': 'Marshall Islands',
  'KI': 'Kiribati', 'NR': 'Nauru', 'TV': 'Tuvalu'
};

export const EAS_CODES: { [key: string]: string } = {
  '0002': 'System Information et Repertoire des Entreprise et des Etablissements: SIRENE',
  '0007': 'Organisationsnummer (Swedish legal entities)',
  '0009': 'SIRET-CODE',
  '0037': 'LY-tunnus',
  '0060': 'Data Universal Numbering System (D-U-N-S Number)',
  '0088': 'EAN Location Code',
  '0096': 'DANISH CHAMBER OF COMMERCE Scheme (EDIRA compliant)',
  '0097': 'FTI - Ediforum Italia, (EDIRA compliant)',
  '0106': 'Vereniging van Kamers van Koophandel en Fabrieken in Nederland (Association of Chambers of Commerce and Industry in the Netherlands), Scheme (EDIRA compliant)',
  '0130': 'Directorates of the European Commission',
  '0135': 'SIA Object Identifiers',
  '0142': 'SECETI Object Identifiers',
  '0151': 'Australian Business Number (ABN) Scheme',
  '0177': 'Odette International Limited',
  '0183': 'Numéro d\'identification suisse des enterprises (IDE), Swiss Unique Business Identification Number (UIDB)',
  '0184': 'DIGSTORG',
  '0188': 'Corporate Number of The Social Security and Tax Number System',
  '0190': 'Dutch Originator\'s Identification Number',
  '0191': 'Centre of Registers and Information Systems of the Ministry of Justice',
  '0192': 'Enhetsregisteret ved Bronnoysundregisterne',
  '0193': 'UBL.BE party identifier',
  '0195': 'Singapore UEN identifier',
  '0196': 'Kennitala - Iceland legal id for individuals and legal entities',
  '0198': 'ERSTORG',
  '0199': 'Legal Entity Identifier (LEI)',
  '0200': 'Legal entity code (Lithuania)',
  '0201': 'Codice Univoco Unità Organizzativa iPA',
  '0202': 'Indirizzo di Posta Elettronica Certificata',
  '0204': 'Leitweg-ID',
  '0208': 'Numero d\'entreprise / ondernemingsnummer / Unternehmensnummer',
  '0209': 'GS1 identification keys',
  '0210': 'CODICE FISCALE',
  '0211': 'PARTITA IVA',
  '0212': 'Finnish Organization Identifier',
  '0213': 'Finnish Organization Value Add Tax Identifier',
  '0215': 'Net service ID',
  '0216': 'OVTcode',
  '0218': 'Unified registration number (Latvia)',
  '0221': 'The registered number of the qualified invoice issuer (Japan)',
  '0230': 'National e-Invoicing Framework (Malaysia)',
  '0235': 'UAE Tax Identification Number (TIN)',
  '9910': 'Hungary VAT number',
  '9913': 'Business Registers Network',
  '9914': 'Österreichische Umsatzsteuer-Identifikationsnummer',
  '9915': 'Österreichisches Verwaltungs bzw. Organisationskennzeichen',
  '9918': 'SOCIETY FOR WORLDWIDE INTERBANK FINANCIAL, TELECOMMUNICATION S.W.I.F.T',
  '9919': 'Kennziffer des Unternehmensregisters',
  '9920': 'Agencia Española de Administración Tributaria',
  '9922': 'Andorra VAT number',
  '9923': 'Albania VAT number',
  '9924': 'Bosnia and Herzegovina VAT number',
  '9925': 'Belgium VAT number',
  '9926': 'Bulgaria VAT number',
  '9927': 'Switzerland VAT number',
  '9928': 'Cyprus VAT number',
  '9929': 'Czech Republic VAT number',
  '9930': 'Germany VAT number',
  '9931': 'Estonia VAT number',
  '9932': 'United Kingdom VAT number',
  '9933': 'Greece VAT number',
  '9934': 'Croatia VAT number',
  '9935': 'Ireland VAT number',
  '9936': 'Liechtenstein VAT number',
  '9937': 'Lithuania VAT number',
  '9938': 'Luxemburg VAT number',
  '9939': 'Latvia VAT number',
  '9940': 'Monaco VAT number',
  '9941': 'Montenegro VAT number',
  '9942': 'Macedonia, the former Yugoslav Republic of VAT number',
  '9943': 'Malta VAT number',
  '9944': 'Netherlands VAT number',
  '9945': 'Poland VAT number',
  '9946': 'Portugal VAT number',
  '9947': 'Romania VAT number',
  '9948': 'Serbia VAT number',
  '9949': 'Slovenia VAT number',
  '9950': 'Slovakia VAT number',
  '9951': 'San Marino VAT number',
  '9952': 'Turkey VAT number',
  '9953': 'Holy See (Vatican City State) VAT number',
  '9957': 'French VAT number',
  '9959': 'Employer Identification Number (EIN, USA)',
  '0147': 'Standard Company Code',
  '0154': 'Identification number of economic subjects: (ICO)',
  '0158': 'Identification number of economic subject (ICO) Act on State Statistics of 29 November 2001, § 27',
  '0170': 'Teikoku Company Code',
  '0194': 'KOIOS Open Technical Dictionary',
  '0203': 'eDelivery Network Participant identifier',
  '0205': 'CODDEST',
  '0217': 'The Netherlands Chamber of Commerce and Industry establishment number',
  '0225': 'FRCTC ELECTRONIC ADDRESS',
  '0240': 'Register of legal persons (in French : Répertoire des personnes morales)'
};

// ISO 3166-1 alpha-2 codes for European countries (used to show Europe first in the country dropdown)
export const EUROPE_ALPHA2: string[] = [
  'NO','SE','DK','FI','IS','DE','FR','IT','ES','PT','NL','BE','LU','AT','CH','GB','IE','PL','CZ','SK','HU','SI','HR','RO','BG','GR','CY','MT','EE','LV','LT'
];
